export const DISHES = 'DISHES';
export const ORDER_DISH_REQUEST = 'ORDER_DISH_REQUEST';
export const ORDER_DISH_ERROR = 'ORDER_DISH_ERROR';

export const ORDERS_DISH_SUCCESS = 'ORDERS_DISH_SUCCESS';


